name: CI

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true
        default: "ROLE:Test"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MY_TAG: ${{ github.event.inputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm test

      - name: Generate Allure report
        if: always()
        run: npm run allure:single

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/index.html
